api:
  base_url: "https://api.mercadolibre.com"
  site_id: "${ML_SITE_ID}"
  search_query: "${SEARCH_QUERY}"
  condition: "${CONDITION}"
  page_size: ${PAGE_SIZE}
  max_records: ${MAX_RECORDS}
  endpoints:
    currencies: "/currencies"
    currency_conversions: "/currency_conversions/search"
    search: "/sites/{site_id}/search"
    items: "/items"
database:
  engine: "postgres"
  host: "${DB_HOST}"
  port: ${DB_PORT}
  name: "${DB_NAME}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  sslmode: "${DB_SSLMODE}"
