version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: meli
      POSTGRES_USER: meli_user
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meli_user -d meli"]
      interval: 5s
      timeout: 5s
      retries: 10

  etl:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./:/app
    command: python -m src.main

volumes:
  pgdata:
